config/routes.rb
Rails.application.routes.draw do
  get 'answers/edit'
  root 'homes#index'
  devise_for :users
  devise_scope :user do
  post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  resources :users
  resources :boards do
    resource :favorites, only: [:create,:destroy]
    get :search, on: :collection
    resources :comments do 
      resources :answers 
    end
  end

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :board
  
  has_many :answers, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    board_id = params[:board_id]
    @comments = Comment.where(board_id:board_id)
    @board = Board.find(params[:board_id])
  end
  
  def show
    @board = Board.find(params[:board_id])
    @comment = Comment.find(params[:id])
    @answer = Answer.new
  end
  
  def new
    @comment = Comment.new
  end
  
  def edit
  end
  
  
  def create
    @comment = Comment.new(comment_params)
    @board = Board.find(params[:board_id])
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to board_comments_path
    else
      redirect_to board_comments_path
    end
  end

  
  
  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to board_comments_path
    else
      render :edit
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to board_comments_path
  end
  
  private
  def comment_params
    params.require(:comment).permit(:title,:name,:question,:board_id,comment_ids: [])
  end
  

  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<div>
<h1>質問編集画面</h1>

  <%= form_for ([@board = Board.find(params[:board_id]), Comment.find(params[:id])]) do |f| %>
  <%= f.hidden_field :board_id, value: @board.id %>
  <div class="form-group">
    <%= f.text_field :name, autofocus: true,class:'form-control', autocomplete: 'name',:placeholder => "name" %>
  </div>
  <div class="form-group">
    <%= f.text_field :title, autofocus: true,class:'form-control', autocomplete: 'title',:placeholder => "title" %>
  </div>
  <div class="form-group">
      <%= f.text_area :question, autofocus: true,class:'form-control', autocomplete: 'question',:placeholder => "question" %>
  </div>
    <%= f.submit '送信', class: 'btn btn-primary' %>
  <% end %>
  <%= link_to '戻る',board_comment_path(@board)%>
</div>

app/views/comments/index.html.erb
<h2>コメント一覧</h2>
  <% @comments.each do |comment| %>
  <div>
    投稿者<%= comment.name %><br>
    <hr>
    <%= link_to board_comment_path(id: comment) do %>
      タイトル<%= comment.title %><br>
    <% end %>
    <hr>
    質問内容<%= comment.question %>
  </div><br>

  <div>
    <%=link_to '編集',edit_board_comment_path(id: comment) %>
    <%=link_to '削除',board_comment_path(id: comment),method: :delete, data:{confirm: '削除しますか'} %>
  </div>
<% end %>
<%= link_to '投稿詳細', board_path(@board)%>

app/views/comments/show.html.erb
<div>
  <h2>コメント詳細</h2>
  <div>
    投稿者<%= @comment.name %><br>
    <hr>
    タイトル<%= @comment.title %><br>
    <hr>
    質問内容<%= @comment.question %>
  </div><br><br>
  <div>
    <%=link_to '質問一覧',board_comments_path %>
  </div>
</div>
<hr>



<div>
  <h3>回答投稿</h3>
  <%= form_with model: [@board,@comment,@answer], local: true do |f| %>
    <%= f.hidden_field :comment_id, {value: @comment.id} %>
    <div class="form-group">
      <%= f.text_field :name, class:'form-control',:placeholder => "name" %>
    </div>
    <div class="form-group">
      <%= f.text_area :content,rows:4, class:'form-control',:placeholder => "content" %>
    </div>
    <div class="text-center">
      <%= f.submit '回答',class:'btn btn-primary'%>
    </div>
    
  <% end %>
</div>