config/routes.rb
Rails.application.routes.draw do
  get 'answers/edit'
  root 'homes#index'
  devise_for :users
  devise_scope :user do
  post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  resources :users
  resources :boards do
    resource :favorites, only: [:create,:destroy]
    get :search, on: :collection
    resources :comments do 
      resources :answers 
    end
  end

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :profile_image 
  has_many :boards, dependent: :destroy
  has_many :favorites,dependent: :destroy       
  has_many :comments
  def self.guest
    find_or_create_by(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
  
  def already_favorited?(board)
    self.favorites.exists?(board_id: board.id)
  end
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def index
  end
  
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(created_at: :desc).page(params[:page]).per(6)
  end

  def show
    if user_signed_in?
      
      @user = User.find(params[:id])
      @boards= params[:tag_id].present? ? Tag.find(params[:tag_id]).boards : @user.boards.all
      @boards = @user.boards.page(params[:page]).per(6)
      
    else
      render template: "homes/index",alert:'ログインしてください'
    end
  end

  def edit
     @user = User.find(params[:id])
  end
  
  def update
     @user = User.find(params[:id])
     @user.update(user_params)
     redirect_to user_path(@user)
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name,:email,:profile,:profile_image)
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!--<div class="form-wrapper">-->
<!--  <h1 style='text-align:center;'>ユーザー詳細画面</h1>-->
<!--  <%#= form_for @user do |f| %>-->
<!--    <div id="cover-user" class="img-profile">-->
<!--      <%# if @user.profile_image_id.present? %>-->
<!--        <%#= image_tag attachment_url(@user, :profile_image),class:'profile-user' %>-->
<!--      <%# else %>-->
<!--        <%#= image_tag 'noimage.png',class:'profile-user'%>-->
<!--      <%# end %>-->
<!--    </div>-->
    
<!--    <%#= f.attachment_field :profile_image, autofocus: true, autocomplete: 'profile-image'%>-->

<!--    <div class="form-group">-->
<!--      <%#= f.label :name,'名前' %>-->
<!--      <%#= f.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control',:placeholder => "name" %>-->
<!--    </div>-->
<!--    <div class="form-group">-->
<!--      <%#= f.label :email %>-->
<!--      <%#= f.email_field :email, autofocus: true, autocomplete: 'email', class: 'form-control',:placeholder => "email" %>-->
<!--    </div>-->
<!--    <div class="form-group">-->
<!--      <%#= f.label :profile,'一言' %>-->
<!--      <%#= f.text_area :profile, autofocus: true, autocomplete: 'profile', class: 'form-control',:placeholder => "コメント入力",rows:3 %>-->
<!--    </div>-->
<!--    <%#= f.submit  class: 'btn btn-primary btn-block' %>-->
<!--   <%# end %>-->
<!--</div>-->

<div class="container jumbotron">
  <div class="row">
    <div class="col-md-6 registration_margin">
      <div class="registration_form">
        <%= form_for @user do |f| %>
          <h1 class="registration">ユーザー詳細画面</h1>
          <div id="cover-user" class="img-profile">
            <% if @user.profile_image_id.present? %>
              <%= image_tag attachment_url(@user, :profile_image),class:'profile-user' %>
            <% else %>
              <%= image_tag 'noimage.png',class:'profile-user'%>
            <% end %>
          </div>
          <%= f.attachment_field :profile_image, autofocus: true, autocomplete: 'profile-image'%>
          <%= f.label :name,'名前' %>
          <%= f.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control',:placeholder => "name" %>
          <%= f.label :email %>
          <%= f.email_field :email, autofocus: true, autocomplete: 'email', class: 'form-control',:placeholder => "email" %>
          <%= f.label :profile,'一言' %>
          <div class="text-profile">
            <%= f.text_area :profile, autofocus: true, autocomplete: 'profile', class: 'form-control',:placeholder => "コメント入力",rows:3 %>
          </div>
          <%= f.submit  class: 'button' %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1 class="text-center user-itiran-margin">ユーザー一覧</h1>
<div class="container">
  <div class="row">
    <% @users.each do |user| %>
        <section class="card">
          <%= link_to user_path(user) do %>
            <% if user.profile_image.present? %>
              <%= image_tag attachment_url(user,:profile_image) ,class:'img-responsive card-img'%>
            <%else%>
              <%= image_tag 'noimage.png' ,class:'img-responsive card-img' %>
            <% end %>
              <div class="card-content">
                <h1 class="card-name"><%=link_to user.name, user_path(user),style:'text-decoration: none; color:#4682b4;' %></h1>
                <div class="card-count">
                   投稿数：<%= user.boards.count %>
                </div>
              </div>
         <% end %>
        </section>
    <% end %>
  </div>
</div>
<div>
  <%= paginate @users %>
</div>

app/views/users/show.html.erb
<div class="ml-auto boards__linkBox tag">
    <%= form_with url: user_path, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id,
                     options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                     {
                       prompt: 'タグで絞り込み',
                       class: 'form-control boards__select',
                       onchange: 'submit(this.form);'
                     }
      %>
    <% end %>
</div>

<div class="display box27">
  <%= attachment_image_tag @user,:profile_image, fallback:"noimage.png",class:'img-responsive image-detail-size'%>
  <div>
    <span class="box-title"><%= @user.name%></span>
    <%=simple_format @user.profile%>
    <div class="display profile-bottom">
      <div class="edit">
        <% if @user.id == current_user.id %>
          <%= link_to '編集',edit_user_path(@user),style:"text-decoration:none; "%>
        <% end %>
      </div
    <div>
      <% if @user.id == current_user.id %>
        <h6><%= @user.email %></h6>
      <% end %>
    </div>
  </div>
</div>


<div class="container">
    <div class="row">
      <% @boards.each do |board| %>
        <!--<section class="card-detail">-->
          <div class="card-detail">
            <%= link_to board_path(board) do %>
              <%= attachment_image_tag board, :image ,class:"img-responsive card-img"%>
            <% end %>
            <div class="parent">
              <span class="span-title"><%= board.title%></span>
            </div>
            <div class="tag-mipage">
              <% board.tags.each do |tag| %>
                <span class="badge badge-primary"><%= tag.name %></span>
              <% end %>
            </div>
            <div class="postuser-link-update">
              <%= board.updated_at.strftime("%Y-%m-%d %H:%M") %>
              <% if current_user.already_favorited?(board) %>
                <%= link_to board_favorites_path(board),method: :delete do %>
                  <i class="fas fa-heart"></i>
                <% end %>
              <% else %>
                <%= link_to board_favorites_path(board),method: :post do %>
                  <i class="far fa-heart"></i>
                <% end %>
              <% end %>
              <%= board.favorites.count %>
            </div>
          </div>
        <!--</section>-->
      <% end %>
    </div>
<div class="pager">
  <%= paginate @boards %>
</div>
</div>