config/routes.rb
Rails.application.routes.draw do
  get 'answers/edit'
  root 'homes#index'
  devise_for :users
  devise_scope :user do
  post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  resources :users
  resources :boards do
    resource :favorites, only: [:create,:destroy]
    get :search, on: :collection
    resources :comments do 
      resources :answers 
    end
  end

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :comment
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  attachment :image
  
  has_many :board_detail, dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :board_tag_relations,dependent: :delete_all
  has_many :tags, through: :board_tag_relations
  has_many :comments, dependent: :destroy
  
  accepts_nested_attributes_for :board_detail, reject_if: :all_blank, allow_destroy: true
end

app/models/board_detail.rb
class BoardDetail < ApplicationRecord
  belongs_to :board
  attachment :image
end

app/models/board_tag_relation.rb
class BoardTagRelation < ApplicationRecord
  belongs_to :board
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :board
  
  has_many :answers, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :board
  
  validates_uniqueness_of :board_id,scope: :user_id
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :board_tag_relations,dependent: :delete_all
  has_many :boards,through: :board_tag_relations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :profile_image 
  has_many :boards, dependent: :destroy
  has_many :favorites,dependent: :destroy       
  has_many :comments
  def self.guest
    find_or_create_by(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
  
  def already_favorited?(board)
    self.favorites.exists?(board_id: board.id)
  end
  
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
   before_action :set_board, only: [:show, :edit, :update,:destroy]
   
  def index
    @boards = params[:tag_id].present? ? Tag.find(params[:tag_id]).boards : Board.all
    @boards = @boards.order(created_at: :desc).page(params[:page]).per(6)
  end
  
    # 検索
  def search
     params[:title].present?
     @boards = Board.where('title LIKE ?', "%#{params[:title]}%")
  end

  def show
    @board_id = Board.find(params[:id]).id
    @board_details = BoardDetail.where(board_id:@board_id)
    @comments = @board.comments
    @comment = Comment.new
  end

  def new
    @board = Board.new
   @board.board_detail.build
  end
  
  def create
    @board = Board.new(board_params)
    @board.user_id = current_user.id
    if @board.save
      redirect_to user_path(@board.user_id)
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    @board.update(board_params)
    redirect_to @board
    binding.pry
  end
  
  def destroy
    @board.user_id = current_user.id
   if  @board.destroy
     redirect_to user_path(@board.user_id),notice:'削除に成功しました'
   else
    render :show
   end
  end
  

  
  
  private
  
  def set_board
      @board = Board.includes(:board_detail).find(params[:id])
  end
  
   def board_params
      params.require(:board).permit(:id,:title,:image,tag_ids: [], board_detail_attributes: [:id, :body,:image,:_destroy])
   end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
  
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました'
  end
  
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(created_at: :desc).page(params[:page]).per(6)
  end

  def show
    if user_signed_in?
      
      @user = User.find(params[:id])
      @boards= params[:tag_id].present? ? Tag.find(params[:tag_id]).boards : @user.boards.all
      @boards = @user.boards.page(params[:page]).per(6)
      
    else
      render template: "homes/index",alert:'ログインしてください'
    end
  end

  def edit
     @user = User.find(params[:id])
  end
  
  def update
     @user = User.find(params[:id])
     @user.update(user_params)
     redirect_to user_path(@user)
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name,:email,:profile,:profile_image)
    end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
   def link_to_add_field(name, f, association, options={})
    # association で渡されたシンボルから、対象のモデルを作る
    # 前回コントローラーで実装したモデルの build にあたる処理
    new_object = f.object.class.reflect_on_association(association).klass.new

    # Javascript 側で配列のインデックス値とする
    # 追加しまくると、インデックス値がかぶりまくるので、
    # 後に Javascript 側でこのインデックス値は現在時刻をミリ秒にした値で置き換えていく
    id = new_object.object_id

    # f はビューから渡されたフォームオブジェクト
    # fields_for で f の子要素を作る
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_form", f: builder)
    end

    # ボタンの設置。classを指定してJavascriptと連動、fields を渡しておいて、
    # ボタン押下時にこの要素(fields)をJavascript側で増やすようにする
    link_to(name, '#', class: "add_field", data: {id: id, fields: fields.gsub("\n","")})

    # Rails3系だと下記のように書けるが、4系で link_to_function は葬られた
    #link_to_function(name, raw("add_field(this, \"#{association}\", \"#{escape_javascript(fields)}\")"), options)
   end

  #削除ボタン
  def link_to_remove_field(name, f, options={})
    # _destroy の hiddenフィールドと削除ボタンを設置
    f.hidden_field(:_destroy) + link_to(name, '#', class: "remove_field")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="js/func.js"></script>
    
    <%= yield :css %>

    <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>  </head>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	
<link href="https://fonts.googleapis.com/css?family=Vollkorn" rel="stylesheet">

  <body>
      <%= render 'shared/header' %>
      <%= yield %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <%= link_to "SONAERU", root_path, class: 'navbar-brand text-light' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item ">
          <%= link_to 'ユーザー一覧',users_path,class:'nav-link text-light'%>
        </li>
        <li class="nav-item">
          <%= link_to 'マイページ',current_user,class:'nav-link text-light'%>
        </li>
        <li class="nav-item">
          <%= link_to '投稿一覧',boards_path,class:'nav-link text-light'%>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to '新規投稿',new_board_path, class: 'nav-link text-light' %>
          </li>
        
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link text-light' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-light' %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-light' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
<hr>
</header>