config/routes.rb
Rails.application.routes.draw do
  get 'answers/edit'
  root 'homes#index'
  devise_for :users
  devise_scope :user do
  post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  resources :users
  resources :boards do
    resource :favorites, only: [:create,:destroy]
    get :search, on: :collection
    resources :comments do 
      resources :answers 
    end
  end

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  attachment :image
  
  has_many :board_detail, dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :board_tag_relations,dependent: :delete_all
  has_many :tags, through: :board_tag_relations
  has_many :comments, dependent: :destroy
  
  accepts_nested_attributes_for :board_detail, reject_if: :all_blank, allow_destroy: true
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
   before_action :set_board, only: [:show, :edit, :update,:destroy]
   
  def index
    @boards = params[:tag_id].present? ? Tag.find(params[:tag_id]).boards : Board.all
    @boards = @boards.order(created_at: :desc).page(params[:page]).per(6)
  end
  
    # 検索
  def search
     params[:title].present?
     @boards = Board.where('title LIKE ?', "%#{params[:title]}%")
  end

  def show
    @board_id = Board.find(params[:id]).id
    @board_details = BoardDetail.where(board_id:@board_id)
    @comments = @board.comments
    @comment = Comment.new
  end

  def new
    @board = Board.new
   @board.board_detail.build
  end
  
  def create
    @board = Board.new(board_params)
    @board.user_id = current_user.id
    if @board.save
      redirect_to user_path(@board.user_id)
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    @board.update(board_params)
    redirect_to @board
    binding.pry
  end
  
  def destroy
    @board.user_id = current_user.id
   if  @board.destroy
     redirect_to user_path(@board.user_id),notice:'削除に成功しました'
   else
    render :show
   end
  end
  

  
  
  private
  
  def set_board
      @board = Board.includes(:board_detail).find(params[:id])
  end
  
   def board_params
      params.require(:board).permit(:id,:title,:image,tag_ids: [], board_detail_attributes: [:id, :body,:image,:_destroy])
   end
end

app/helpers/boards_helper.rb
module BoardsHelper
   def link_to_add_field(name, f, association, options={})
    # association で渡されたシンボルから、対象のモデルを作る
    # 前回コントローラーで実装したモデルの build にあたる処理
    new_object = f.object.class.reflect_on_association(association).klass.new

    # Javascript 側で配列のインデックス値とする
    # 追加しまくると、インデックス値がかぶりまくるので、
    # 後に Javascript 側でこのインデックス値は現在時刻をミリ秒にした値で置き換えていく
    id = new_object.object_id

    # f はビューから渡されたフォームオブジェクト
    # fields_for で f の子要素を作る
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_form", f: builder)
    end

    # ボタンの設置。classを指定してJavascriptと連動、fields を渡しておいて、
    # ボタン押下時にこの要素(fields)をJavascript側で増やすようにする
    link_to(name, '#', class: "add_field", data: {id: id, fields: fields.gsub("\n","")})

    # Rails3系だと下記のように書けるが、4系で link_to_function は葬られた
    #link_to_function(name, raw("add_field(this, \"#{association}\", \"#{escape_javascript(fields)}\")"), options)
   end

  #削除ボタン
  def link_to_remove_field(name, f, options={})
    # _destroy の hiddenフィールドと削除ボタンを設置
    f.hidden_field(:_destroy) + link_to(name, '#', class: "remove_field")
  end
end

app/views/boards/_board_detail_form.html.erb
<div class="nested-fields text ">
  <div class="parent">
    <!--<p><%#=f.label :body,'説明' ,style:'margin-bottom:0px;'%></p>-->
    <div class="form-group text-body ">
      <%= f.text_area:body,class:'form-control',rows:5,cols:1,:placeholder => "説明文を入力"  %><br>
    </div>
      <%= f.attachment_field :image ,class:'board_detail_image'%>
  </div>
    <%= f.hidden_field :id%>
    <%= link_to_remove_field( "remove task", f,{}) %>
</div>

app/views/boards/_form.html.erb
<%=form_with(model: board, local: true) do |f|%>
  <div id="cover-image" class="relative">
    <% if board.image_id.present? %>
      <%= image_tag attachment_url(board, :image),class:'board-image',style:'width:100%;height:300px;'%>
    <% else %>
      <%= image_tag 'none_image.jpg',class:'board-image',style:'width:100%;height:300px;'%>
    <% end %>
    <i class="fa fa-camera"></i>
  </div>
    <%= f.attachment_field :image %><br>
  <div class="form-group">
    <%= f.text_field :title,class:'form-control',:placeholder => "タイトル" %><br>
  </div>
  <%= f.hidden_field :id %>
  <hr>

  <div class="board_details">
    <%= f.fields_for :board_detail do |df| %>
      <%= render partial: "board_detail_form",locals: {f: df } %>
    <% end %>
    
    
    <div class="links tag-tsuika">
      <%= link_to_add_field( "追加", f, :board_detail ,{})%>
    </div>
    
  <div class="form-group">
    <span>タグ</span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class="form-check">
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>
    
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<div class="container">
  <div class="row" style="background-color: white;">
    <div class="col-md-6 col-md-offset-3", style="margin: 0 auto;">
      <h4>新規投稿</h4>
      <%= render 'form',board: @board %>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<div class="ml-auto boards__linkBox tag select-light">
  <div class="search">
    <%= form_with url: search_boards_path, id: :form1 ,method: :get, local: true do |f| %>
        <div class="form-group">
          <%= f.text_field :title ,class:'form-control', id:'sbox'%>
          <%= f.submit :検索 ,id:'sbtn' %>
        </div>
    <% end %>
  </div>
    
    <%= form_with url: boards_path, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id,
                     options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                     {
                       prompt: 'タグで絞り込み',
                       class: 'form-control boards__select',
                       onchange: 'submit(this.form);'
                     }
      %>
    <% end %>
</div>



<div class="container">
  <h1 class="text-center">投稿一覧画面</h1>
    <div class="row">
      <% @boards.each do |board| %>
        <div class="card-itiran">
          <%= link_to board_path(board) do %>
            <%= attachment_image_tag board, :image ,class:"img-responsive card-img-itiran"%>
          <% end %>
            <div class="itiran-title">
              <%= board.title %>
            </div>
          <div class="parent">
            <%= link_to user_path(board.user.id) do %> 
              <%= attachment_image_tag board.user, :profile_image,fallback: "noimage.png",class:"card-img-itiran-profile"%>
            <% end %>
            <div class="user-link-update">
              <%= link_to board.user.name ,user_path(board.user.id)%><br>
              <%= board.updated_at.strftime("%Y-%m-%d %H:%M") %>
            </div>
          </div>
          
          <div class="favorite tag">
              <% board.tags.each do |tag| %>
                <span class="badge badge-primary"><%= tag.name %></span>
              <% end %>
            <% if current_user.already_favorited?(board) %>
              <%= link_to board_favorites_path(board),style:"text-decoration: none;",method: :delete do %>
                <i class="fas fa-heart" ></i>
              <% end %>
            <% else %>
              <%= link_to board_favorites_path(board),style:"text-decoration: none;",method: :post do %>
                <i class="far fa-heart" style="text-decoration:none";></i>
              <% end %>
            <% end %>
            <%= board.favorites.count %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="pager">
      <%= paginate @boards %>
    </div>
  </div>

app/views/boards/new.html.erb
<div class="container">
  <div class="row" style="background-color: white;">
    <div class="col-md-8 col-md-offset-2", style="margin: 0 auto;">
      <h4>新規投稿</h4>
      <%= render 'form',board: @board %>
    </div>
  </div>
</div>

app/views/boards/search.html.erb
<div class="ml-auto boards__linkBox tag">
    <%= form_with url: search_boards_path, method: :get, local: true do |f| %>
        <%= f.text_field :title %>
        <%= f.submit :検索 %>
    <% end %>
    
    <%= form_with url: boards_path, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id,
                     options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                     {
                       prompt: 'タグで絞り込み',
                       class: 'form-control boards__select',
                       onchange: 'submit(this.form);'
                     }
      %>
    <% end %>
</div>
<div class="container">
  <h1 class="text-center">投稿一覧画面</h1>
    <div class="row">
      <% @boards.each do |board| %>
        <div class="card-itiran">
          <%= link_to board_path(board) do %>
            <%= attachment_image_tag board, :image ,class:"img-responsive card-img-itiran"%>
          <% end %>
          <div class="itiran-title">
              <%= board.title %>
          </div>
          <div class="parent">
            <%= link_to user_path(board.user.id) do %> 
              <%= attachment_image_tag board.user, :profile_image,fallback: "noimage.png",class:"card-img-itiran-profile"%>
            <% end %>
            <div class="user-link-update">
              <%= link_to board.user.name ,user_path(board.user.id)%><br>
              <%= board.updated_at.strftime("%Y-%m-%d %H:%M") %>
            </div>
          </div>
          
          <div class="favorite tag">
              <% board.tags.each do |tag| %>
                <span class="badge badge-primary"><%= tag.name %></span>
              <% end %>
            <% if current_user.already_favorited?(board) %>
              <%= link_to board_favorites_path(board),style:"text-decoration: none;",method: :delete do %>
                <i class="fas fa-heart" ></i>
              <% end %>
            <% else %>
              <%= link_to board_favorites_path(board),style:"text-decoration: none;",method: :post do %>
                <i class="far fa-heart" style="text-decoration:none";></i>
              <% end %>
            <% end %>
            <%= board.favorites.count %>
          </div>
        </div>
      <% end %>
    </div>

  </div>

app/views/boards/show.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h1><%= @board.title%></h1>
    <div class="title-image-center">
      <%= attachment_image_tag @board, :image,class:'image-width' %>
    </div>
    
    
    <span><%= @board.user.name %>さんの投稿</span>
    <% if current_user.already_favorited?(@board) %>
      <%= link_to board_favorites_path(@board),method: :delete do %>
        <i class="fas fa-heart"></i>
      <% end %>
    <% else %>
      <%= link_to board_favorites_path(@board),method: :post do %>
        <i class="far fa-heart"></i>
      <% end %>
    <% end %>
    <%= @board.favorites.count %>
    <div class="make">
      <h2>手順</h2>
    </div>
      <% @board_details.each do |board_detail| %>
        <div class="text-show ">
          <%= attachment_image_tag board_detail,:image ,class:'image-width' %>
          <p class="font-size"><%= board_detail.body%></p>
        </div>
      <% end %>
  </div>
  
  <%= link_to '質問一覧画面',board_comments_path(@board) %>

</div>
      <% if @board.user.id == current_user.id %>
        <%= link_to "編集",edit_board_path(@board), class:"btn btn-success"%>
      <% end %>
      <% if @board.user.id == current_user.id %>
        <%= link_to "削除", board_path(@board),method: :delete, data: {confirm: "削除しますか？"},class:'btn btn-danger delete'%>
      <% end %>
<%= link_to user_path(@board.user) do %>
  <%= @board.user.name %>さんのページへ
<% end %>

<h1>質問入力</h1>
<div>
   <%= form_for [@board, @comment] do |f| %>
<%= f.hidden_field :board_id, value: @board.id %>
  <div class="form-group">
    <%= f.text_field :name, autofocus: true,class:'form-control', autocomplete: 'name',:placeholder => "name" %>
  </div>
  <div class="form-group">
    <%= f.text_field :title, autofocus: true,class:'form-control', autocomplete: 'title',:placeholder => "title" %>
  </div>
  <div class="form-group">
      <%= f.text_area :question, autofocus: true,class:'form-control', autocomplete: 'question',:placeholder => "question" %>
  </div>
    <%= f.submit '送信', class: 'btn btn-primary' %>
  <% end %>
</div>